apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-driver-validation
  name: nvidia-driver-validation
  namespace: openshift-sro
  annotations:
    callback: nvidia-driver-validation
spec:
#  serviceAccount: nvidia-readonly
#  serviceAccountName: nvidia-readonly
  tolerations:
    - operator: Exists
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  restartPolicy: Never
  containers:
    - name: cuda-vector-add
      image: "quay.io/openshift-psap/cuda-vector-add:v0.1"
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA  
          value: "cuda>=5.0"
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
  nodeSelector:
    node-role.kubernetes.io/worker: ""
    feature.node.kubernetes.io/pci-10de.present: "true"
